# Generated by Django 2.1.3 on 2018-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
